### ISSUE TITLE
no audio

### ISSUE THREAD

**Issue by SimonePie** [Meebleeps/MeeBleeps-Freaq-FM-Synth#7]
Hi, congratulations on your super project ... a squeeze of Arduino!
As soon as I saw the video on YouTube I fell in love with it and of course I tried to make a prototype. Thanks to the Monitor function I have seen that the pots and buttons work correctly but I do not get any signal from pin D9 .... any suggestions?
Congratulations again for the project!

**Comment by SimonePie** [comment]
Risolto!! ..errore mio!

**Comment by Meebleeps** [comment]
glad to hear it is working! 😊 Molto bene!
